name: Renew

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 18:00
    - cron: "0 11 * * 1"

jobs:
  renew:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Script
        run: pnpm start
